version: "3.9"

services:
#  redis:
#    image: redis:7
#    container_name: redis-cache
#    ports:
#      - "6379:6379"
#    networks:
#      - app-network
#    restart: always
#    healthcheck:
#      test: ["CMD", "redis-cli", "ping"]
#      interval: 5s
#      timeout: 5s
#      retries: 5
#
#  db:
#    image: postgres:15
#    container_name: postgres-db
#    restart: always
#    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: 1234
#      POSTGRES_DB: my_db
#    ports:
#      - "5432:5432"
#    networks:
#      - app-network
#    healthcheck:
#      test: ["CMD-SHELL", "pg_isready -U postgres"]
#      interval: 5s
#      retries: 5

  app:
    build: .
    container_name: java-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/my_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    networks:
      - app-network
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy

networks:
  app-network:
    driver: bridge
